### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by Elfangor93** [ThomasFinnern/J_LangMan4ExtDev#1]
I get the following error when I try to install your component:

![grafik](https://user-images.githubusercontent.com/39154009/188306408-cd24a9c1-5537-4d94-b4ed-be64713ddbfe.png)

### Environment:
![grafik](https://user-images.githubusercontent.com/39154009/188306436-f0413471-df22-4539-9c9a-858f90c4e437.png)

**Comment by ThomasFinnern** [comment]
mysql does not accept a default value for type "text" when in strict mode. 
See https://stackoverflow.com/questions/3466872/why-cant-a-text-column-have-a-default-value-in-mysql
[Why can't a text column have a default value in MySQL?](https://stackoverflow.com/questions/3466872/why-cant-a-text-column-have-a-default-value-in-mysql)

**Comment by ThomasFinnern** [comment]
fixed in version 0.20.0.0
