### ISSUE TITLE
Error when creating a new project

### ISSUE THREAD

**Issue by Elfangor93** [ThomasFinnern/J_LangMan4ExtDev#2]
Once I have installed the component and try to add my first project, I get the following error after I saved the form for project creation:

![grafik](https://user-images.githubusercontent.com/39154009/188306980-f4b68208-b50f-4f27-804f-c1eb00bb2e1f.png)

### Environment
![grafik](https://user-images.githubusercontent.com/39154009/188306910-3d06f3c6-9117-4874-80d6-0d2e4aa74143.png)

**Comment by ThomasFinnern** [comment]
mysql does not accept a default value for type "text" when in strict mode. So the table is not created

**Comment by ThomasFinnern** [comment]
fixed in vrsion 0.20.0.0
